format = """
$time $directory$git_branch$git_status$python$nodejs$container$line_break$jobs$status$cmd_duration$character"""

[time]
disabled = false
format = '[ $time]($style) '
style = "bold #89b4fa"

[directory]
style = "bold #cba4f7"
truncation_length = 3
format = '[ $path]($style) '

[git_branch]
format = '[ $branch]($style) '
style = "bold #89b4fa"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "#f38ba8"

[cmd_duration]
min_time = 0
format = '[ $duration]($style) '
style = "bold #f9e2af"

[status]
disabled = false
format = '[$status]($style) '
style = "bold #f38ba8"

[jobs]
format = '[ $number]($style) '
style = "bold #f9e2af"

[python]
format = '[ $version]($style) '
style = "bold #a6e3a1"

[nodejs]
format = '[ $version]($style) '
style = "bold #a6e3a1"

[container]
format = '[ $name]($style) '
style = "bold #89b4fa"

[character]
success_symbol = "[❯](bold #a6e3a1)"
error_symbol = "[❯](bold #f38ba8)"
